Update emailNotify

diff --git a/emailNotify b/emailNotify
--- a/emailNotify
+++ b/emailNotify
@@ -1,19 +1,39 @@
-node {	
-	try {
-	stage('Init') { 
-	echo "Init Stage"
-	} 
-	stage('Gate') {
-	echo "Gate Stage"
-	}
-	currentBuild.result = 'SUCCESS' 
-	} catch (Exception err) {
-	echo 'This will run only if failed'
-	currentBuild.result = 'FAILURE'
-	} 
-	finally { 
-	mail to: 'kdwebs91@gmail.com',
-	subject: "BUILD STATUS: ${currentBuild.result} ${currentBuild.currentResult}|| Pipeline Details: ${currentBuild.fullDisplayName}",
-	body: """<p>EXECUTED: Job <b>\'${env.JOB_NAME}:${env.BUILD_NUMBER})\'</b></p><p>View console output at "<a href="${env.BUILD_URL}"> ${env.JOB_NAME}:${env.BUILD_NUMBER}</a>"</p> <p><i>(Build log is attached.)</i></p>""" 
-	} 
-	} 
+def notifySuccessful() {
+  emailext attachLog: true, 
+  body: """<p>EXECUTED: Job <b>\'${env.JOB_NAME}:${env.BUILD_NUMBER})\'</b></p><p>View console output at "<a href="${env.BUILD_URL}"> ${env.JOB_NAME}:${env.BUILD_NUMBER}</a>"</p> <p><i>(Build log is attached.)</i></p>""", 
+    compressLog: true,
+    recipientProviders: [[$class: 'DevelopersRecipientProvider'], 
+     [$class: 'RequesterRecipientProvider']],
+    replyTo: 'do-not-reply@company.com', 
+    subject: "Status: ${currentBuild.result?:'SUCCESS'} - job \'${env.JOB_NAME}:${env.BUILD_NUMBER}\'", 
+    to: 'kdwebs91@gmail.com,ashok-kumar.gandham@capgemini.com,kushal.karmakar@capgemini.com,chaitanya.a.reddy@capgemini.com,vijay.q.kumar@capgemini.com'
+    
+}
+
+def notifyFailed() {
+  emailext attachLog: true, 
+  body: """<p>EXECUTED: Job <b>\'${env.JOB_NAME}:${env.BUILD_NUMBER})\'</b></p><p>View console output at "<a href="${env.BUILD_URL}"> ${env.JOB_NAME}:${env.BUILD_NUMBER}</a>"</p> <p><i>(Build log is attached.)</i></p>""", 
+    compressLog: true,
+    recipientProviders: [[$class: 'DevelopersRecipientProvider'], 
+     [$class: 'RequesterRecipientProvider']],
+    replyTo: 'do-not-reply@company.com', 
+    subject: "Status: ${currentBuild.result?:'FAILURE'} - job \'${env.JOB_NAME}:${env.BUILD_NUMBER}\'", 
+    to: 'kdwebs91@gmail.com,ashok-kumar.gandham@capgemini.com,kushal.karmakar@capgemini.com,chaitanya.a.reddy@capgemini.com,vijay.q.kumar@capgemini.com'
+}
+
+node {
+        try {
+        stage('Init') {           
+            echo "Init Stage"
+            sh "exit 1"
+        } 
+        stage('Gate') {
+        echo "Gate Stage"
+        }
+        notifySuccessful()           
+        } catch (Exception err) {
+            echo 'This will run only if failed'
+            notifyFailed()           
+        }  
+                        
+  }    
